# Generated by Django 4.2.20 on 2025-04-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('database', '0001_initial'), ('database', '0002_alter_stores_options_remove_stores_end_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50, verbose_name='Код магазина')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('cluster', models.CharField(max_length=50, verbose_name='Округ')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('store_format', models.CharField(max_length=2, verbose_name='Формат склада')),
                ('begin_date', models.DateField(verbose_name='Дата открытия')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
