# Generated by Django 4.2.20 on 2025-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код магазина'),
        ),
    ]
