# Generated by Django 4.2.20 on 2025-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_products_product_id_alter_stores_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.CharField(max_length=50, unique=True, verbose_name='Код акции')),
                ('type', models.CharField(max_length=100, verbose_name='Тип акции')),
            ],
            options={
                'verbose_name': 'Промо-акция',
                'verbose_name_plural': 'Промо-акции',
            },
        ),
    ]
