# Generated by Django 4.2.20 on 2025-04-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код акции'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код магазина'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sales', models.FloatField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.products')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.promo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stores')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('date', 'store', 'product', 'promo'), name='unique_sale_entry'),
        ),
    ]
